export const erpNavigation = [
  { id: 'dashboard', label: 'Dashboard', icon: 'dashboard', permission: 'view_dashboard' },
  { id: 'master-data', label: 'Master Data', icon: 'layers', permission: 'view_all' },
  { id: 'procurement', label: 'Procurement', icon: 'truck', permission: 'view_procurement' },
  { id: 'erp-analytics', label: 'ERP Analytics', icon: 'chart', permission: 'view_analytics' },
  { id: 'blockchain', label: 'Verification Ledger', icon: 'blocks', permission: 'view_blockchain' },
  { id: 'orders', label: 'Sales Orders', icon: 'cart', permission: 'view_orders' },
  { id: 'invoices', label: 'Invoices', icon: 'document', permission: 'view_orders' },
  { id: 'customers', label: 'Customers', icon: 'users', permission: 'view_customers' },
  { id: 'inventory', label: 'Inventory', icon: 'box', permission: 'view_inventory' },
  { id: 'finance', label: 'Finance', icon: 'wallet', permission: 'view_finance' },
  { id: 'gst', label: 'GST Compliance', icon: 'receipt', permission: 'view_analytics' },
  { id: 'accounting', label: 'Accounting', icon: 'calculator', permission: 'view_analytics' },
  { id: 'tds', label: 'TDS Management', icon: 'percent', permission: 'view_analytics' },
  { id: 'demand-forecast', label: 'Demand Forecast', icon: 'trending', permission: 'view_analytics' },
  { id: 'invoice-scanner', label: 'Invoice Scanner', icon: 'camera', permission: 'view_orders' },
  { id: 'ai-assistant', label: 'AI Assistant', icon: 'robot', permission: 'view_analytics' },
  { id: 'hr-management', label: 'HR Management', icon: 'users', permission: 'view_all' },
  { id: 'manufacturing', label: 'Manufacturing', icon: 'box', permission: 'view_inventory' },
  { id: 'project-management', label: 'Projects', icon: 'clipboard', permission: 'view_analytics' },
  { id: 'document-management', label: 'Documents', icon: 'document', permission: 'view_all' },
  { id: 'asset-management', label: 'Assets', icon: 'layers', permission: 'view_inventory' },
  { id: 'workflow-approvals', label: 'Approvals', icon: 'lock', permission: 'view_all' },
  { id: 'support', label: 'Support', icon: 'headset', permission: 'view_dashboard' },
  { id: 'audit', label: 'Audit Log', icon: 'clipboard', permission: 'view_audit' },
  { id: 'settings', label: 'Settings', icon: 'settings', permission: 'view_dashboard' },
]
